[workspace]
resolver = "3"
members = ["crawler", "tf-idf-indexer", "utils"]

[dependencies]
sqlx = { version = "0.8.6", features = ["postgres", "runtime-tokio-rustls", "migrate"] }
tokio = { version = "1.47.1", features = ["full"] }
flexi_logger = "0.31.5"
log = "0.4.28"
