[package]
name = "tf-idf-indexer"
version = "0.1.0"
edition = "2024"

[dependencies]
criterion = "0.7.0"
once_cell = "1.21.3"
ordered-float = "5.1.0"
scraper = "0.24.0"
sqlx = { version = "0.8.6", features = ["postgres", "runtime-tokio-rustls"] }
stop-words = "0.9.0"
